#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  finalizers:
    - finalizers.packageinstall.packaging.carvel.dev/delete
  name: #@ "snyk-scanner-" + data.values.name
  namespace: tap-install
spec:
  packageRef:
    refName: snyk.scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0-beta.6
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
    - secretRef:
        name: #@ "snyk-scanner-" + data.values.name
---
apiVersion: v1
stringData:
  values.yml: |
    namespace: tanzu-java-web-app
    targetImagePullSecret: registry-credentials
    snyk:
      tokenSecret:
        name: snyk-token-secret
    metadataStore:
      caSecret:
        importFromNamespace: "" #! since both Snyk and Grype both enable store, one must leave importFromNamespace blank
kind: Secret
metadata:
  name: #@ "snyk-scanner-" + data.values.name
  namespace: tap-install
type: Opaque