#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ if hasattr(data.values, "scanpolicy") and data.values.scanpolicy == "snyk":
#@ def config():
---
namespace: #@ data.values.name
targetImagePullSecret: registries-credentials
snyk:
  tokenSecret:
    name: snyk-token-secret
metadataStore:
  caSecret:
    importFromNamespace: "" 
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  finalizers:
    - finalizers.packageinstall.packaging.carvel.dev/delete
  name: grype-scanner-snyk
  namespace: tap-install
spec:
  packageRef:
    refName: snyk.scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: "1.0.0-beta.6"
      prereleases: {}
  serviceAccountName: tap-install-sa
  values:
    - secretRef:
        name: #@ "grype-scanner-snyk-" + data.values.name
---
apiVersion: v1
stringData:
  values.yml: #@ yaml.encode(config())
kind: Secret
metadata:
  name: grype-scanner-snyk
  namespace: tap-install
type: Opaque
#@ end