# ---
# apiVersion: secretgen.carvel.dev/v1alpha1
# kind: SecretImport
# metadata:
#   name: git-https
#   annotations:
#     tekton.dev/git-0: https://github.com  
# spec:
#   fromNamespace: tap-install

#@ if/end hasattr(data.values, "scanpolicy") and data.values.scanpolicy == "snyk":
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: snyk-token-secret
spec:
  fromNamespace: tap-install
