#@ if/end hasattr(data.values, "scanpolicy") and data.values.scanpolicy == "snyk":
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: snyk-token-secret
spec:
  fromNamespace: tap-install
