#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-https
  annotations:
    tekton.dev/git-0: https://github.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: chrisaveria
  password: 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
